AznaCity/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('city.urls')),
    path('accounts/', include('accounts.urls')),
    # Third-Party urls
    path('ckeditor/', include('ckeditor_uploader.urls')),

]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path, re_path

from accounts import views

# -*- coding: utf-8 -*-

app_name = 'accounts'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('profile/details', views.profile_details, name='profile_details'),
    path('profile/edit/', views.profile_edit, name='profile_edit'),
    path('register', views.register_user, name='register_user'),

    path('post/add/', views.add_post_view, name='add_post_view'),
    path('post-list', views.post_list, name='post_list'),
    re_path(r'^post-edit/(?P<slug>[-\w]+)/$', views.post_edit, name='post_edit'),
]

city/urls.py
from django.urls import path, re_path

from city import views

app_name = 'city'
urlpatterns = [
    path('', views.homepage, name='home_page'),
    # path('gardeshgari/', views.all_gardesh, name='all_gardesh'),
    # path('gardeshgari/details/<int:place_id>/', views.place_details, name='places_details'),
    re_path(r'^category/(?P<slug>[-\w]+)/$', views.category, name='unique_slug'),
    # path('main/Kaveh/<slug:slug>/', views.details, name='details'),
    re_path(r'^p/(?P<slug>[-\w]+)/$', views.place_details, name='place_details'),
    re_path(r'^p/(?P<slug>[-\w]+)/add$', views.add_sub_cat, name='add_sub_cat'),
    path('like/<int:pk_p>/<int:pk_c>/', views.like_post, name='like_post'),
    path('dislike/<int:pk_p>/<int:pk_c>/', views.dislike_post, name='dislike_post'),
]

city/forms.py
from django import forms

from city.models import Place, Soghat, SOGHAT_CATEGORY, Hotel, HOTEL_RES_CATEGORY


class AddPlaceForm(forms.ModelForm):
    class Meta:
        model = Place
        fields = ('name', 'image', 'description')

    name = forms.CharField(label='نام', max_length=50,
                           widget=forms.TextInput(
                               attrs={'class': 'rounded border border-gray-300 text-gray-800 w-full mt-4 '
                                               'mb-8 px-3 py-2 block'}))

    description = forms.CharField(label='توضیحات',
                                  widget=forms.Textarea(
                                      attrs={'class': 'rounded border border-gray-300 w-full '
                                                      'text-gray-800 mt-4 mb-8 '
                                                      'px-3 py-2 block'}))
    image = forms.CharField(label='عکس', max_length=50,
                            widget=forms.FileInput(
                                attrs={'class': 'mt-4 mb-8 block'}))


class AddSoghatForm(forms.ModelForm):
    class Meta:
        model = Soghat
        fields = ('name', 'description', 'image', 'sub_category')

    name = forms.CharField(label='نام', max_length=50,
                           widget=forms.TextInput(
                               attrs={'class': 'rounded border border-gray-300  text-gray-800 w-full mt-4 '
                                               'mb-8 px-3 py-2 block'}))

    description = forms.CharField(label='توضیحات',
                                  widget=forms.Textarea(
                                      attrs={'class': 'rounded border border-gray-300 w-full  '
                                                      'text-gray-800 mt-4 mb-8 '
                                                      'px-3 py-2 block'}))
    image = forms.CharField(label='عکس', max_length=50,
                            widget=forms.FileInput(
                                attrs={'class': 'mt-4 mb-8 block'}))

    sub_category = forms.CharField(label='دسته بندی', max_length=50,
                                   widget=forms.Select(choices=SOGHAT_CATEGORY, attrs={'class': 'rounded border '
                                                                                                'border-gray-300 mt-4 '
                                                                                                'mb-8 block '
                                                                                                ' text-gray-800'}))


class AddHotelForm(forms.ModelForm):
    class Meta:
        model = Hotel
        fields = ('name', 'image', 'sub_category', 'phone', 'address', 'description')

    name = forms.CharField(label='نام', max_length=50,
                           widget=forms.TextInput(
                               attrs={
                                   'class': 'rounded border border-gray-300 text-gray-800 w-full mt-4 '
                                            'mb-8 px-3 py-2 block'}))

    description = forms.CharField(label='توضیحات',
                                  widget=forms.Textarea(
                                      attrs={'class': 'rounded border border-gray-300 w-full  '
                                                      'text-gray-800 mt-4 mb-8 '
                                                      'px-3 py-2 block'}))
    image = forms.CharField(label='عکس', max_length=50,
                            widget=forms.FileInput(
                                attrs={'class': 'mt-4 mb-8 block'}))

    sub_category = forms.CharField(label='دسته بندی', max_length=50,
                                   widget=forms.Select(choices=HOTEL_RES_CATEGORY,
                                                       attrs={'class': 'rounded border border-gray-300 mt-4 '
                                                                       'mb-8 block  text-gray-800'}))
    address = forms.CharField(label='آدرس', max_length=50,
                              widget=forms.Textarea(
                                  attrs={'class': 'rounded border border-gray-300  text-gray-800 w-full '
                                                  'md:w-96 mt-4 mb-8 px-3 py-2 block'}))
    phone = forms.CharField(label='تلفن', max_length=50,
                            widget=forms.TextInput(
                                attrs={'class': 'rounded border border-gray-300  text-gray-800 w-full '
                                                'md:w-96 mt-4 mb-8 px-3 py-2 block'}))


class CommentForm(forms.Form):
    fields = ('fullname', 'email', 'comment')

    fullname = forms.CharField(label='نام و نام خانوادگی', required=False, max_length=50,
                               widget=forms.TextInput(
                                   attrs={'class': 'rounded border border-gray-300 text-gray-800 '
                                                   'mt-4 mb-8 px-3 py-2 text-sm w-full block'}))
    email = forms.EmailField(label='ایمیل', max_length=50, required=False,
                             widget=forms.TextInput(attrs={'class': 'rounded border border-gray-300 '
                                                                    'text-gray-800  mt-4 mb-8 px-3 py-2 '
                                                                    'text-sm w-full block'}))
    # phone = forms.CharField(label='موبایل', max_length=11, required=True,
    #                         widget=forms.TextInput(attrs={'class': 'rounded border border-gray-300 '
    #                                                                'text-gray-800  mt-4 mb-8 px-3 py-2 '
    #                                                                'text-sm w-full block'}))
    comment = forms.CharField(label='متن پیام', required=True,
                              widget=forms.Textarea(
                                  attrs={'class': 'rounded border border-gray-300 '
                                                  'text-gray-800 mt-4 mb-8 '
                                                  'px-3 py-2 w-full block'}))

# 'placeholder': 'لطفاً نام خود را وارد نمایید'
# 'placeholder': 'لطفاً ایمیل خود را وارد نمایید'
# 'placeholder': 'لطفاً شماره همراه خود را وارد نمایید'

city/views.py
from itertools import chain

from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponseRedirect
from django.urls import reverse

from .forms import AddPlaceForm, AddSoghatForm, AddHotelForm, CommentForm
from .models import City, Place, Soghat, Category, Martyrs, Hotel, Comment, IpClass

categorys = Category.objects.filter(parent=None)


def homepage(request):
    # print(categorys)
    places = Place.objects.all()
    city = City.objects.get(name='ازنا')
    gardesh = Place.objects.filter(category__slug='گردشگری', is_access=True)[:4]
    tarikhi = Place.objects.filter(category__slug='تاریخی-مذهبی', is_access=True)[:4]
    karkhane = Place.objects.filter(category__slug='کارخانجات', is_access=True)[:4]
    roosta = Place.objects.filter(category__slug='روستا', is_access=True)[:4]
    soghats = Soghat.objects.filter(is_access=True)
    martyrs = Martyrs.objects.filter(is_access=True)
    hotel_res = Hotel.objects.filter(is_access=True)
    for i in places:
        des = i.description[:50]
    context = {
        'categorys': categorys,
        'places': places,
        'city': city,
        'gardesh': gardesh,
        'tarikhi': tarikhi,
        'karkhane': karkhane,
        'roosta': roosta,
        'soghats': soghats,
        'martyrs': martyrs,
        'hotel': hotel_res,
    }
    return render(request, 'city/home_page.html', context=context)


# def all_gardesh(request):
#     all_gardeshgari = Place.objects.filter(category='T')
#     context = {
#         'all_gardeshgari': all_gardeshgari
#
#     }
#     return render(request, 'city/category.html', context=context)


def place_details(request, slug):

    list1 = [Place, Soghat, Hotel, Martyrs]
    for li in list1:
        case1 = li.objects.filter(slug=slug)
        if case1.exists():
            case = li.objects.get(slug=slug)

    ip = get_client_ip(request)
    if not IpClass.objects.filter(ip=ip).exists():
        IpClass.objects.create(ip=ip)

    case.views.add(IpClass.objects.get(ip=ip))

    context = {
        'case': case,
        'categorys': categorys,
    }

    # ******************* Start Comment *************************
    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            fullname = request.POST.get('fullname')
            email = request.POST.get('email')
            message = request.POST.get('comment')
            comment = Comment(content_object=case, fullname=fullname, email=email, comment=message)
            comment.save()
            # try:
            #     comment = comment_form.save(commit=False)
            #     comment.content_object = case
            #     comment.save()
            #     error_form = 'نظر شما با موفقیت ثبت شد.'
            # except Exception as e:
            #     error_form = str(e)
            #     print('error to save: ', str(e))
            # context['error_form'] = error_form
    else:
        comment_form = CommentForm()

    comments = Comment.objects.filter(object_id=case.id, confirm=True)
    context['comments'] = comments
    context['comment_form'] = comment_form
    # ******************* End Comment ***************************

    return render(request, 'city/places_details.html', context=context)


def category(request, slug):
    cat = Category.objects.get(slug=slug)

    place = Place.objects.filter(category__slug=slug, is_access=True)
    soghat = Soghat.objects.filter(category__slug=slug, is_access=True)
    hotel = Hotel.objects.filter(category__slug=slug, is_access=True)
    martyr = Martyrs.objects.filter(category__slug=slug, is_access=True)
    cats = list(chain(place, soghat, hotel, martyr))

    context = {
        'cat': cat,
        'cats': cats,
        'categorys': categorys,
    }

    # if cats:
    #     cat_name = cats[0].category.name
    #     cat = cats[0].category
    #     # print('cat: ', cat)
    #     context['cat_name'] = cat_name
    #     context['cat'] = cat

    return render(request, 'city/category.html', context=context)


@login_required
def add_sub_cat(request, slug):
    context = {
        'categorys': categorys,
        'slug': slug,
    }
    print('slug is: ', slug)
    if request.method == 'POST':
        if slug == 'سوغات':
            add_form = AddSoghatForm(request.POST, request.FILES)
        elif slug == 'هتل':
            add_form = AddHotelForm(request.POST, request.FILES)
        else:
            add_form = AddPlaceForm(request.POST, request.FILES)
        if add_form.is_valid():
            try:
                new = add_form.save(commit=False)
                name = request.POST.get('name')
                new.slug = "-".join(name.split())
                new.category = Category.objects.get(slug=slug)
                new.save()
                return HttpResponseRedirect(reverse('city:unique_slug', kwargs={'slug': slug}))
            except Exception as e:
                context['error_form'] = str(e)
                print('error to save: ', str(e))
        else:
            print('form oninvalid')
    else:
        if slug == 'سوغات':
            add_form = AddSoghatForm()
        # elif Q(slug == 'هتل') | Q(slug == 'رستوران'):
        elif slug == 'هتل' or slug == 'رستوران':
            add_form = AddHotelForm()
        else:
            add_form = AddPlaceForm()

    context['add_form'] = add_form

    return render(request, 'city/add_sub_cat.html', context=context)


def get_client_ip(request):
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        ip = x_forwarded_for.split(',')[0]
    else:
        ip = request.META.get('REMOTE_ADDR')
    return ip


def like_post(request, pk_p, pk_c):
    list1 = [Place, Soghat, Hotel, Martyrs]
    for li in list1:
        case1 = li.objects.filter(id=pk_p)
        if case1.exists():
            case = get_object_or_404(case1, id=pk_p)
            print('case: ', case1)

    comment = Comment.objects.get(id=request.POST.get('comment_id'))

    ip = get_client_ip(request)

    if not IpClass.objects.filter(ip=ip).exists():
        IpClass.objects.create(ip=ip)
    if comment.likes.filter(id=IpClass.objects.get(ip=ip).id).exists():
        comment.likes.remove(IpClass.objects.get(ip=ip))
    else:
        comment.likes.add(IpClass.objects.get(ip=ip))

    return HttpResponseRedirect(case.get_absolute_url())


def dislike_post(request, pk_p, pk_c):
    list1 = [Place, Soghat, Hotel, Martyrs]
    for li in list1:
        case1 = li.objects.filter(id=pk_p)
        if case1.exists():
            case = get_object_or_404(case1, id=pk_p)

    comment = Comment.objects.get(id=request.POST.get('comment_id'))

    ip = get_client_ip(request)

    if not IpClass.objects.filter(ip=ip).exists():
        IpClass.objects.create(ip=ip)
    if comment.dislikes.filter(id=IpClass.objects.get(ip=ip).id).exists():
        comment.dislikes.remove(IpClass.objects.get(ip=ip))
    else:
        comment.dislikes.add(IpClass.objects.get(ip=ip))

    return HttpResponseRedirect(case.get_absolute_url())

city/templates/city/partial/footer.html
<footer class="footer bg-primary">
    <div class="footer-container flex justify-start flex-wrap font-vazir gap-16 mx-12 py-4">
        <div class="footer-cat-1 w-50  md:w-1/6">
            <p class="footer-cat-list-title font-bold text-gray-800 border-b-2 border-yellow-400 py-4">دسترسی سریع</p>
            <ul class="footer-cat-list text-gray-100 mt-4">
                {% for c in categorys %}
                    <li class="p-1 transition h-8 ease-in duration-200 transform hover:text-gray-800 hover:-translate-x-2">
                        <a href="{{ c.get_absolute_url }}">{{ c.name }}</a></li>
                {% endfor %}
            </ul>
        </div>

        <div class="footer-cat-2 w-50 md:w-1/6">
            <p class="footer-cat-list-title font-bold text-gray-800 border-b-2 border-yellow-400 py-4">لینک های مفید</p>
            <ul class="footer-cat-list text-gray-100 mt-4">
                <li class="p-1 transition ease-in duration-200 transform hover:text-gray-800 hover:-translate-x-2"><a
                        href="#">شهرداری ازنا</a></li>
                <li class="p-1 transition ease-in duration-200 transform hover:text-gray-800 hover:-translate-x-2"><a
                        href="#">ازنا خبر</a></li>
                <li class="p-1 transition ease-in duration-200 transform hover:text-gray-800 hover:-translate-x-2"><a
                        href="#">استانداری</a></li>
                <li class="p-1 transition ease-in duration-200 transform hover:text-gray-800 hover:-translate-x-2"><a
                        href="https://baratisafe.com">گاوصندوق</a></li>
            </ul>
        </div>
    </div>
<div class="py-4 text-right mx-12">
    <span class="font-vazir text-sm text-gray-200">فیلمها و تصاویر خود را با موضوع مرتبط با شهرستان ازنا به آی دی تلگرام DiyareAzna@ ارسال نمایید.</span>
</div>
    <div class="h-12 bg-gray-800 p-2 text-center"><span class="font-vazir text-sm text-gray-100 flex justify-center">تمامی حقوق متعلق به سایت دیار ازنا می باشد . استفاده از مطالب سایت با ذکر منبع بلامانع است.</span></div>
</footer>

city/templates/city/partial/header.html
<header class="header bg-header-back-mobile md:h-96 md:bg-header-back bg-cover">
    <div class="header-container">
        {% include 'city/partial/navigation.html' %}
        <div class="header-center flex mt-16 p-4">
            <div class="header-container-right header-container-item px-8 w-1/3">
{#                <img src="../../../static/city/logo1.jpg" alt="ازنا"#}
{#                     class="header-container-logo header-container-item">#}
                <input class="header-container-search font-vazir text-sm w-1/2 focus:bg-gray-100 rounded-full px-3 py-2" type="text" placeholder="جستجو در سایت">
            </div>
            <div class="header-container-center header-container-item w-1/3 flex justify-center items-center">
                <h2 class="header-container-title font-nastaliq text-4xl text-white">ازنا پایتخت کوهنوردی ایران</h2>
            </div>
            <div class="header-container-left header-container-item">
                {#        <a href="{% url 'city:home_page' %}" class="header-container-home-link">#}
                {#          <i class="fa fa-home header-container-home "></i>#}
                {#        </a>#}
            </div>
        </div>
    </div>

</header>

city/templates/city/partial/navigation.html
<nav class="navbar navbar-expand-lg">
    <div class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
         aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <div class="bar1"></div>
        <div class="bar2"></div>
        <div class="bar3"></div>
        {#        <button data-toggle="collapse" data-target="#navbarSupportedContent">&times;</button>#}
    </div>
    <div class="collapse navbar-collapse flex" id="navbarSupportedContent">
        <ul class="navbar-nav navigation-menu text-gray-100 text-sm font-vazir flex p-4">
            <li class="nav-item mr-8 border-b-4 border-transparent transition ease-in-out duration-300 py-1 hover:border-yellow-400 hover:text-gray-800">
                <a href="{% url 'city:home_page' %}" class="nav-link">
                    <i class="fa fa-home ml-2"></i>
                    <span>صفحه اصلی</span></a>
            </li>
            {% for c in categorys %}
                <li class="nav-item mr-8 border-b-4 border-transparent transition ease-in-out duration-300 py-1 hover:border-yellow-400 hover:text-gray-800">
                    <a href="{{ c.get_absolute_url }}" class="nav-link flex items-center">
                        {% if c.icon_name %}<i class="{{ c.icon_name }} ml-2"></i>{% endif %}
                        <span>{{ c.name }}</span>
                    </a>
                </li>
            {% endfor %}
            {#            <li class="nav-item mr-8 border-b-4 border-transparent transition ease-in-out duration-300 py-1 hover:border-yellow-400 hover:text-gray-800">#}
            {#                <a href="{% url 'city:home_page' %}" class="nav-link"><i class="fa fa-home ml-2"></i> صفحه اصلی</a>#}
            {#            </li>#}
            {#            <li class="nav-item mr-8 border-b-4 border-transparent transition ease-in-out duration-300 py-1 hover:border-yellow-400 hover:text-gray-800">#}
            {#                <a href="{% url 'city:unique_slug' slug='گردشگری' %}" class="nav-link"><i#}
            {#                        class="fas fa-umbrella-beach ml-2"></i>گردشگری</a>#}
            {#            </li>#}
            {#            <li class="nav-item mr-8 border-b-4 border-transparent transition ease-in-out duration-300 py-1 hover:border-yellow-400 hover:text-gray-800">#}
            {#                <a href="{% url 'city:unique_slug' slug='تاریخی-مذهبی' %}" class="nav-link"><i#}
            {#                        class="fas fa-mosque ml-2"></i>تاریخی-مذهبی</a>#}
            {#            </li>#}
            {#            <li class="nav-item mr-8 border-b-4 border-transparent transition ease-in-out duration-300 py-1 hover:border-yellow-400 hover:text-gray-800">#}
            {#                <a href="{% url 'city:unique_slug' slug='کارخانجات' %}" class="nav-link"><i#}
            {#                        class="fa fa-industry ml-2"></i>کارخانجات</a>#}
            {#            </li>#}
            {#            <li class="nav-item mr-8 border-b-4 border-transparent transition ease-in-out duration-300 py-1 hover:border-yellow-400 hover:text-gray-800">#}
            {#                <a href="{% url 'city:unique_slug' slug='بزرگان' %}" class="nav-link"><i#}
            {#                        class="fas fa-user-graduate ml-2"></i>بزرگان</a>#}
            {#            </li>#}
            {#            <li class="nav-item mr-8 border-b-4 border-transparent transition ease-in-out duration-300 py-1 hover:border-yellow-400 hover:text-gray-800">#}
            {#                <a href="{% url 'city:unique_slug' slug='شهدا' %}" class="nav-link"><i class="fa fa-user ml-2"></i>شهدا</a>#}
            {#            </li>#}
            {#            <li class="nav-item mr-8 border-b-4 border-transparent transition ease-in-out duration-300 py-1 hover:border-yellow-400 hover:text-gray-800">#}
            {#                <a href="{% url 'city:unique_slug' slug='هتل' %}" class="nav-link"><i#}
            {#                        class="fa fa-hotel ml-2"></i>هتل</a>#}
            {#            </li>#}
            {#            <li class="nav-item mr-8 border-b-4 border-transparent transition ease-in-out duration-300 py-1 hover:border-yellow-400 hover:text-gray-800">#}
            {#                <a href="{% url 'city:unique_slug' slug='رستوران' %}" class="nav-link flex">#}
            {#                    <i class="fa fa-cutlery ml-2"></i>#}
            {#                    <img class="text-white" src="../../../../media/categorys/icon/eating.png" alt="eating">#}
            {#                    رستوران#}
            {#                </a>#}
            {#            </li>#}
            {#             <li class="nav-item mr-8 border-b-4 border-transparent transition ease-in-out duration-300 py-1 hover:border-yellow-400 hover:text-gray-800">#}
            {#                <a href="{% url 'city:unique_slug' slug='ازناگردی' %}" class="nav-link"><i#}
            {#                        class="fa fa-city ml-2"></i>ازناگردی</a>#}
            {#            </li>#}
            {#             <li class="nav-item mr-8 border-b-4 border-transparent transition ease-in-out duration-300 py-1 hover:border-yellow-400 hover:text-gray-800">#}
            {#                <a href="{% url 'city:unique_slug' slug='اخبار-و-مقالات' %}" class="nav-link"><i#}
            {#                        class="fa fa-blog ml-2"></i>اخبار و مقالات</a>#}
            {#            </li>#}
            <li class="nav-item mr-8 border-b-4 border-transparent transition ease-in-out duration-300 py-1 hover:border-yellow-400 hover:text-gray-800">
                <a href="" class="nav-link"><i class="fa fa-info-circle ml-2"></i>درباره ما</a>
            </li>
            <li class="nav-item mr-8 border-b-4 border-transparent transition ease-in-out duration-300 py-1 hover:border-yellow-400 hover:text-gray-800">
                <a href="" class="nav-link"><i class="fa fa-phone-square ml-2"></i>ارتباط با ما</a>
            </li>


        </ul>
        <div class="mr-auto ml-4">
            <ul class="text-gray-100 text-sm font-vazir flex gap-2 p-4">
                {% if user.is_authenticated %}
                    <li class="nav-item border-b-4 border-transparent transition ease-in-out duration-300 py-1 hover:border-yellow-400 hover:text-gray-800">
                        <a class="" href="{% url 'accounts:profile_details' %}"><i class="fa fa-user ml-2"></i>{{ user.username }}</a>
                    </li>
                    <li class="nav-item border-b-4 border-transparent transition ease-in-out duration-300 py-1 hover:border-yellow-400 hover:text-gray-800">
                        <a href="{% url 'accounts:logout' %}" class="nav-link"><i class="fa fa-sign-out ml-2"></i>خروج</a>
                    </li>
                {% else %}
                    <li class="nav-item border-b-4 border-transparent transition ease-in-out duration-300 py-1 hover:border-yellow-400 hover:text-gray-800">
                        <a href="{% url 'accounts:login' %}" class="nav-link"><i class="fa fa-user ml-2"></i>ورود</a>
                    </li>
                    <li class="nav-item border-b-4 border-transparent transition ease-in-out duration-300 py-1 hover:border-yellow-400 hover:text-gray-800">
                        <a href="{% url 'accounts:register_user' %}" class="nav-link">ثبت نام</a>
                    </li>
                    </ul>
                {% endif %}
        </div>
    </div>

</nav>