AznaCity/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('city.urls')),
    path('accounts/', include('accounts.urls')),
    # Third-Party urls
    path('ckeditor/', include('ckeditor_uploader.urls')),

]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path, re_path

from accounts import views

# -*- coding: utf-8 -*-

app_name = 'accounts'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('profile/details', views.profile_details, name='profile_details'),
    path('profile/edit/', views.profile_edit, name='profile_edit'),
    path('register', views.register_user, name='register_user'),

    path('post/add/', views.add_post_view, name='add_post_view'),
    path('post-list', views.post_list, name='post_list'),
    re_path(r'^post-edit/(?P<slug>[-\w]+)/$', views.post_edit, name='post_edit'),
]

city/urls.py
from django.urls import path, re_path

from city import views

app_name = 'city'
urlpatterns = [
    path('', views.homepage, name='home_page'),
    # path('gardeshgari/', views.all_gardesh, name='all_gardesh'),
    # path('gardeshgari/details/<int:place_id>/', views.place_details, name='places_details'),
    re_path(r'^category/(?P<slug>[-\w]+)/$', views.category, name='unique_slug'),
    # path('main/Kaveh/<slug:slug>/', views.details, name='details'),
    re_path(r'^p/(?P<slug>[-\w]+)/$', views.place_details, name='place_details'),
    re_path(r'^p/(?P<slug>[-\w]+)/add$', views.add_sub_cat, name='add_sub_cat'),
    path('like/<int:pk_p>/<int:pk_c>/', views.like_post, name='like_post'),
    path('dislike/<int:pk_p>/<int:pk_c>/', views.dislike_post, name='dislike_post'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User

MALE = 1
FEMALE = 2
GENDER_CHOICES = ((MALE, 'مرد'), (FEMALE, 'زن'))


class Profile(models.Model):
    """
    Represents a user's profile
    """

    class Meta:
        verbose_name = 'نمایه کاربری'
        verbose_name_plural = 'نمایه کاربری'

    user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name='حساب کاربری')
    # important fields that are stored in User model:
    #   first_name, last_name, email, date_joined

    mobile = models.CharField('تلفن همراه', max_length=11)

    gender = models.IntegerField('جنسیت', choices=GENDER_CHOICES, null=True, blank=True)

    birth_date = models.DateField('تاریخ تولد', null=True, blank=True)
    address = models.TextField('آدرس', null=True, blank=True)
    profile_image = models.ImageField('تصویر', upload_to='users/profile_images/', null=True, blank=True)

    def __str__(self):
        if self.user.get_full_name():
            return self.user.get_full_name()
        else:
            return self.user.username

#
# class NewsLetter(models.Model):
#     class Meta:
#         verbose_name = 'خبرنامه'
#         verbose_name_plural = 'خبرنامه'
#
#     email = models.EmailField('ایمیل')
#
#     def __str__(self):
#         return self.email

accounts/forms.py
from django import forms
from news.models import News
from accounts.models import Profile, GENDER_CHOICES
from django.forms import ModelForm, Textarea
from ckeditor_uploader.fields import RichTextUploadingField
from django.contrib.auth.forms import UserChangeForm


class PostForm(ModelForm):
    class Meta:
        model = News
        fields = ('title', 'slug', 'category', 'image', 'text', 'study_time')
        # widgets = {
        #     'title': Textarea(attrs={'cols': 80, 'rows': 1, 'class': 'p-1'}),
        #     'slug': Textarea(attrs={'cols': 80, 'rows': 1, 'class': 'p-1'}),
        # }


class MyUserForm(UserChangeForm):
    class Meta(UserChangeForm.Meta):
        fields = ['first_name', 'last_name', 'email']

    first_name = forms.CharField(label='نام', max_length=50,
                                 widget=forms.TextInput(
                                     attrs={
                                         'class': 'rounded border border-gray-300 w-full text-gray-800 mt-4 '
                                                  'mb-8 px-3 py-2 block'}))

    last_name = forms.CharField(label='نام خانوادگی', max_length=50,
                                widget=forms.TextInput(
                                    attrs={
                                        'class': 'rounded border border-gray-300 w-full text-gray-800 mt-4 '
                                                 'mb-8 px-3 py-2 block'}))
    email = forms.CharField(label='ایمیل', max_length=50,
                            widget=forms.TextInput(
                                attrs={
                                    'class': 'rounded border border-gray-300 text-gray-800 w-full mt-4 '
                                             'mb-8 px-3 py-2 block'}))

    password = None


class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        fields = ['mobile', 'gender', 'address', 'profile_image']

    mobile = forms.CharField(label='موبایل', max_length=50,
                             widget=forms.TextInput(
                                 attrs={
                                     'class': 'rounded border border-gray-300 w-full text-gray-800 mt-4 '
                                              'mb-8 px-3 py-2 block'}))

    gender = forms.CharField(label='جنسیت', max_length=50,
                             widget=forms.Select(choices=GENDER_CHOICES, attrs={'class': 'rounded border '
                                                                                         'border-gray-300 mt-4 '
                                                                                         'mb-8 block '
                                                                                         ' text-gray-800'}))
    address = forms.CharField(label='آدرس', max_length=50,
                              widget=forms.Textarea(
                                  attrs={'class': 'rounded border border-gray-300  text-gray-800 w-full '
                                                  ' mt-4 mb-8 px-3 py-2 block'}))

    profile_image = forms.FileInput()

accounts/views.py
from django.shortcuts import render

from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.contrib.auth.models import User
from django.urls import reverse
from django.contrib import messages

from news.models import News
from .forms import MyUserForm, ProfileForm, PostForm
from .models import Profile
from city.models import Category

# -*- coding: utf-8 -*-

categorys = Category.objects.all


def login_view(request):
    next_url = request.GET.get('next')

    # search_form = SearchForm(data=request.GET)

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            # Successful login
            login(request, user)
            redirect_url = next_url if next_url else reverse('city:home_page')
            return HttpResponseRedirect(redirect_url)
        else:
            # undefined user or wrong password
            context = {
                'categorys': categorys,

                'username': username,
                # 'search_form': search_form,
                'login_error': 'کاربری با این مشخصات یافت نشد!'
            }
    else:
        print('request is get')
        context = {
            'categorys': categorys,

            # 'search_form': search_form,
        }
    # search_form_method(request, context)
    return render(request, 'accounts/login.html', context)


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('city:home_page'))


@login_required
def profile_details(request):
    profile = request.user.profile
    # search_form = SearchForm(data=request.GET)
    context = {
        'categorys': categorys,

        # 'search_form': search_form,
        'profile': profile,
    }
    # search_form_method(request, context)
    return render(request, 'accounts/profile_details.html', context)


@login_required
def profile_edit(request):
    profile = request.user.profile
    if request.method == 'POST':
        user_form = MyUserForm(request.POST, instance=request.user)
        profile_form = ProfileForm(request.POST, files=request.FILES, instance=request.user.profile)
        if user_form.is_valid() and profile_form.is_valid():
            try:
                user_form.save()
                profile_form.save()
                return HttpResponseRedirect(reverse('accounts:profile_details'))
            except Exception as e:
                print('form is invalid ...', str(e))
        else:
            print('error ...')
    else:
        user_form = MyUserForm(instance=request.user)
        profile_form = ProfileForm(instance=request.user.profile)

    # search_form = SearchForm(data=request.GET)
    context = {
        'user_form': user_form,
        'profile_form': profile_form,
        'profile': profile,
        # 'search_form': search_form,
        'categorys': categorys,

    }
    # search_form_method(request, context)
    return render(request, 'accounts/profile_edit.html', context)


def register_user(request):
    # search_form = SearchForm(data=request.GET)
    context = {
        'categorys': categorys,

        # 'search_form': search_form,
    }
    # search_form_method(request, context)
    if request.method == 'POST':
        try:
            # f_name = request.POST.get('f_name')
            # l_name = request.POST.get('l_name')
            # email = request.POST.get('email')
            mobile = request.POST.get('mobile')
            # gender = request.POST.get('gender')
            username = request.POST.get('username')
            password = request.POST.get('password')
            user = User.objects.create_user(username=username, password=password)
            Profile.objects.create(user=user, mobile=mobile)
            context['message_in_register'] = 'حساب کابری شما با موفقیت ثبت شد'
        except Exception as e:
            print('error in register: ', str(e))
            context['message_in_register'] = 'لطفاً اطلاعات خواسته شده را به درستی وارد نمایید.'
    return render(request, 'accounts/register_form.html', context=context)


@login_required()
def post_list(request):
    post = News.objects.filter(author=request.user.profile).order_by('-pub_date')
    print('post :', post)
    # search_form = SearchForm(data=request.GET)

    context = {
        'post': post,
        'categorys': categorys,

        # 'search_form': search_form,
    }
    # search_form_method(request, context)

    return render(request, 'accounts/post_list_page.html', context=context)


@login_required()
def add_post_view(request):
    # search_form = SearchForm(data=request.GET)

    context = {
        'categorys': categorys,

        # 'search_form': search_form,
    }

    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        slug = request.POST.get('slug')

        news = News.objects.filter(slug=slug)

        if form.is_valid():
            if len(news) == 0:
                instance = form.save(commit=False)
                instance.author = request.user.profile
                if instance.category.parent is not None:
                    instance.save()
                    print('form submit')
                    return redirect('accounts:post_list')
                else:
                    context[
                        'error_message'] = 'در ثبت اطلاعات مشکلی پیش آمده است! لطفاً برای انتخاب دسته بندی از زیر گروه استفاده کنید.'
            else:
                context[
                    'error_message'] = 'در ثبت اطلاعات مشکلی پیش آمده است! ممکن است پستی با این اسلاگ قبلاَ ثبت شده باشد. لطفاً اسلاگ را تصحیح کنید!'
        else:
            print('form invalid')
            context['error_message'] = 'در ثبت اطلاعات مشکلی پیش آمده است! لطفاً خطاها را اصلاح کنید.'

    else:
        form = PostForm()

    context['form'] = form

    # search_form_method(request, context)

    return render(request, 'accounts/add_post_page.html', context=context)


@login_required()
def post_edit(request, slug):
    # search_form = SearchForm(data=request.GET)
    instance = get_object_or_404(News, slug=slug)
    form = PostForm(request.POST, request.FILES, instance=instance)
    context = {
        'instance': instance,
        # 'search_form': search_form,
        'categorys': categorys,

    }
    if request.method == 'POST':
        if form.is_valid():
            instance = form.save(commit=False)
            instance.save()
            messages.success(request, "Post Saved")
            return HttpResponseRedirect(reverse('accounts:post_list'))
        else:
            print('form invalid')

    else:
        form = PostForm(instance=instance)

    context['form'] = form

    # search_form_method(request, context)

    return render(request, 'accounts/post_edit.html', context)

accounts/templates/accounts/add_post_page.html
{% extends 'city/base.html' %}
{% load static %}
{#{% load jformat %}#}
{#{% load humanize %}#}
{% block extra_headers %}

{% endblock %}
{% block title %}اضافه کردن پست {{ super }}{% endblock %}
{% block body %}

    <div class="add-news-page cryptoi-container">
        <div class="profile-detail-container">
            {% if error_message %}
                <div class="submit-message-container">
                    <div class="message {% if error_message %}negative{% endif %}">
                        <span id="submit-message">{{ error_message }}</span>
                    </div>
                </div>
            {% endif %}
            {% include 'accounts/partial/_dashboard.html' %}

            <div class="add-news-container">
                <div class="title-container justify-content-center">
                    <h4 class="title text-right mr-2">فرم اضافه کردن پست جدید</h4>
                </div>
                <hr>
                <form class="form-group" action="{% url 'accounts:add_post_view' %}" method="post" id="frm-add-post"
                      enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_table }}
                    {{ form.media }}
                    <input type="submit" value="ثبت" class="btn btn-success submit-form  btn m-3">
                </form>
            </div>
        </div>
    </div>
    {#    <script>#}
    {#        CKEDITOR.replace('text');#}
    {#    </script>#}
    {% block extra_body %}
        <script src="{% static 'city/js/slugify.js' %}"></script>
        <script src="{% static 'city/js/ckeditor.js' %}"></script>
        <script src="{% static 'city/js/add-p.js' %}"></script>
    {% endblock %}
{% endblock %}

accounts/templates/accounts/base_accounts.html
{% extends 'city/base.html' %}
{% load static %}
{#{% block extra_css %}#}
{#    <link rel="stylesheet" type="text/css" href="{% static 'cryptocur/css/accounts.css' %}">#}
{#{% endblock %}#}

{#    <div class="base-account-page">#}
{% block body %}
    <div class="dashboard-container ">
        <div class="details-image-container text-center">
            {% if profile.profile_image %}
                <img src="{{ profile.profile_image.url }}" alt="{{ profile.user.get_full_name }}"
                     class="profile-image">
            {% else %}
                <img src="{% static 'city/images/profile-image.png' %}"
                     alt="{{ profile.user.get_full_name }}" class="profile-image">
            {% endif %}
            <hr>
        </div>
        {% if user.is_staff %}
            <div class="details-work-container dash-item">
                <ul class="item-list">
                    <li class="add-item"><a class="add-new-item add-news" href="{% url 'accounts:add_news_view' %}">اضافه
                        کردن خبر</a></li>
                    <li class="add-item"><a class="add-new-item add-article" href="">اضافه کردن مقاله</a></li>
                    <li class="add-item"><a class="add-new-item add-article" href="{% url 'accounts:news_list' %}">خبرهای
                        من</a></li>
                    <li class="add-item"><a class="add-new-item add-article" href="">مقاله های من</a></li>
                </ul>
            </div>
        {% endif %}
        <div class="profile-button text-center">
            <a href="#">
                <button class="btn btn-dark"><i class="fa fa-edit ml-2"></i> ویرایش نمایه</button>
            </a>
            <a href="#">
                <button class="btn btn-warning"><i class="fa fa-key ml-2"></i> تغییر گذرواژه</button>
            </a>
        </div>
    </div>
    {#    </div>#}

    {% block extra_body %}{% endblock %}
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'city/base.html' %}
{% load static %}
{#{% load jformat %}#}
{#{% load humanize %}#}
{% block extra_headers %}
{% endblock %}
{% block title %}ورود کاربر {{ super }}{% endblock %}
{% block body %}
    <div class="login-page-container">
        <div class="container-form mx-auto font-vazir md:max-w-screen-lg px-4 md:px-2 my-8 flex justify-center">
            <div class="container-form-login w-96">
                <form action="" method="post" name="frm_login" class="form-login shadow bg-white rounded-lg p-4">
                    {% csrf_token %}
                    <h5 class="title-form text-center my-4">ورود به حساب کاربری</h5>
                    <img class="w-64 h-64 mx-auto my-8 flex justify-center" src="{% static 'city/images/login.png' %}" alt="ورود به حساب کاربری">
                    {% if login_error %}
                        <div class="alert alert-danger text-center">
                            {{ login_error }}
                        </div>
                    {% endif %}
                    <div class="tamasha w-full border border-gray-400 my-4 rounded bg-white overflow-hidden flex">
                        <i class="fa fa-address-card phone-icon text-gray-300 p-2"></i>
                        <input type="text" name="username" class="form-control text-xs p-2 w-full h-full border-0 focus:border-0" placeholder="نام کاربری">
                    </div>
                    <div class="tamasha w-full border border-gray-400 my-4 rounded overflow-hidden flex">
                        <i class="fa fa-key phone-icon text-gray-300 p-2"></i>
                        <input type="password" name="password" class="form-control text-xs p-2  w-full h-full focus:border-opacity-0" placeholder="گذرواژه">
                    </div>

                    <div class="form-group remember-me text-right">
                        <input type="checkbox" class="checkbox-input ml-2">
                        <label class="text-sm text-gray-600" for="form-check-label ">مرا به خاطر بسپار</label>
                    </div>

                    <div class="button-submit flex justify-end my-8">
                        <button type="submit" class="btn btn-primary w-32 h-8 rounded bg-primary text-white hover:shadow transition ease-in duration-150">ورود</button>
                    </div>

                    <div class="other-link text-right text-sm flex flex-col text-gray-600 gap-4">
                        <a class="hover:text-gray-800 transition ease-in duration-150" href="{% url 'accounts:register_user' %}"><i class="fa fa-user-plus pl-2"
                                                                        ></i>ثبت نام</a>
                        <a class="hover:text-gray-800 transition ease-in duration-150" href="#"><i class="fas fa-lock-open pl-2"></i>رمز عبور خود را فراموش
                            کرده ام !</a>
                    </div>

                </form>
            </div>
        </div>
    </div>


{% endblock %}

accounts/templates/accounts/post_edit.html
{% extends 'city/base.html' %}
{% load static %}
{#{% load jformat %}#}
{#{% load humanize %}#}
{% block extra_headers %}

{% endblock %}
{% block title %}ویرایش پست {{ instance.title }} {{ super }}{% endblock %}
{% block body %}

    <div class="add-news-page cryptoi-container">
        {% if error_message %}
            <div class="submit-message-container">
                <div class="message {% if error_message %}negative{% endif %}">
                    <span id="submit-message">{{ error_message }}</span>
                </div>
            </div>
        {% endif %}
        {% include 'accounts/partial/_dashboard.html' %}

        <div class="add-news-container">
            <div class="title-container justify-content-center">
                <h4 class="title text-right">فرم ویرایش</h4>
            </div>
            <hr>
            <form class="form-group" action="{% url 'accounts:post_edit' instance.slug %}" method="post" id="frm-add-post"
                  enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_table }}
                {{ form.media }}
                <input type="submit" value="ثبت" class="btn btn-success submit-form  btn m-3">
            </form>
        </div>
    </div>
    {#    <script>#}
    {#        CKEDITOR.replace('text');#}
    {#    </script>#}
    {% block extra_body %}
        <script src="{% static 'city/js/slugify.js' %}"></script>
        <script src="{% static 'city/js/ckeditor.js' %}"></script>
        <script src="{% static 'city/js/add-p.js' %}"></script>
    {% endblock %}
{% endblock %}

accounts/templates/accounts/post_list_page.html
{#{% extends 'cryptocur/base_page.html' %}#}
{% extends 'city/base.html' %}
{% load static %}
{#{% load jformat %}#}
{#{% load humanize %}#}
{% block extra_headers %}
{% endblock %}
{% block title %}پست های من{{ super }}{% endblock %}

{% block body %}
    <div class="news-list-page cryptoi-container">
        <div class="profile-detail-container">
            {% include 'accounts/partial/_dashboard.html' %}
            <div class="news-list-container">
                <div class="news-title-container justify-content-center">
                    <h4 class="title text-right">لیست پست های من</h4>
                </div>
                <hr>

                <ul class="list-group text-right mt-3">
                    {% if post %}
                        {% for p in post %}
                            <li class="list-item">
                                <a class="list-item-link" target="_blank"
                                   href="{{ p.get_absolute_url }}">{{ p.title }}</a>
                                <a class="list-item-edit-link" href="{% url 'accounts:post_edit' p.slug %}">ویرایش</a>
                            </li>
                        {% endfor %}
                    {% else %}
                        <li class="list-item list-item-empty-post"><span>شما تاکنون هیچ پستی نداشته اید!</span></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
{% endblock %}

accounts/templates/accounts/profile_details.html
{% extends 'city/base.html' %}
{% load static %}
{#{% load jformat %}#}
{#{% load humanize %}#}
{% block extra_headers %}
{% endblock %}
{% block title %}نمایه کاربری {{ super }}{% endblock %}
{% block body %}
    <div class="profile-page">
        <div class="profile-detail-container mx-auto font-vazir md:max-w-screen-lg px-2 my-8 grid grid-cols-3 gap-2">
            {% include 'accounts/partial/_dashboard.html' %}
            <div class="details-container bg-white border rounded col-span-3 md:col-span-2">
                <div class="border-b p-4 bg-gray-200 font-bold">
                    <h4 class="profile-detail-title details-item">اطلاعات حساب کاربری</h4>
                </div>
                <div class="details-name details-item p-4 text-gray-500 text-sm">
                    <div class="flex gap-1">
                        <div class="col-2 text-right">
                            <span class="text-muted">
                                <i class="fa fa-user"></i>
                                نام کاربری:
                            </span>
                        </div>
                        <div class="col-4 input-value font-bold text-gray-700">
                            {{ user.username }}
                        </div>
                    </div>
                    <div class="flex gap-1 my-6">
                        <div class="">
                            <span class="details-name-title"><i class="fa fa-address-card ml-2">
                            </i>نام و نام خانوادگی :
                            </span>
                        </div>
                        <div class="details-name-value font-bold text-gray-700">
                            <span>
                                {% if profile.user.get_full_name %}{{ profile.user.get_full_name }}
                                {% else %}{{ profile.user.username }}{% endif %}
                            </span>
                        </div>
                    </div>
                    <div class="my-6 flex gap-1">
                        <div class="text-gray-500">
                            <span class="details-name-title text-muted"><i class="fa fa-birthday-cake ml-2"> </i>تاریخ
                                تولد
                                :</span>
                        </div>
                        <div class="details-name-value font-bold text-gray-700">
                            <span>{{ profile.birth_date|date:"Y/n/j" }}</span></div>
                    </div>

                    <div class="my-6 flex gap-1">
                        <div class="col-xl-3 col-sm-5">
                            <span class="details-name-title text-muted"><i class="fa fa-mobile-phone ml-2"></i> تلفن
                                همراه
                                :</span>
                        </div>
                        <div class="details-name-value font-bold text-gray-700"><span>{{ profile.mobile }}</span></div>
                    </div>

                    <div class="my-6 flex gap-1">
                        <div class="col-xl-3 col-sm-5">
                            <span class="details-name-title text-muted"><i class="fa fa-envelope ml-2"></i>ایمیل
                                :</span>
                        </div>
                        <div class="details-name-value font-bold text-gray-700"><span>{{ profile.user.email }}</span>
                        </div>
                    </div>

                    <div class="my-6 flex gap-1">
                        <div class="col-xl-3 col-sm-5">
                            <span class="details-name-title text-muted"><i class="fa fa-home ml-2"></i>آدرس :</span>
                        </div>
                        <div class="details-name-value font-bold text-gray-700 item-text-box"><span>{% if profile.address %}
                            {{ profile.address }}{% endif %}</span></div>
                    </div>

                    <div class="my-6 flex gap-1">
                        <div class="col-xl-3 col-sm-5">
                            <span class="details-name-title text-muted"><i class="fa fa-vcard-o ml-2"></i>بیوگرافی
                                :</span>
                        </div>
                        <div class="details-name-value font-bold text-gray-700"><span></span></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

accounts/templates/accounts/register_form.html
{% extends 'city/base.html' %}
{% load static %}
{#{% load jformat %}#}
{#{% load humanize %}#}
{% block extra_headers %}
{% endblock %}
{% block title %}ثبت نام {{ super }}{% endblock %}
{% block body %}
    <div class="register-page-container">
        <div class="container-form mx-auto font-vazir md:max-w-screen-lg px-4 md:px-2 my-8 flex justify-center">
            <div class="container-form-register w-96">
                <form action="" method="post" name="frm_register" class="form-register shadow bg-white rounded-lg p-4">
                    {% csrf_token %}
                    <h5 class="title-form text-center my-4">ثبت نام در سایت</h5>
                    <img class="w-64 h-64 mx-auto my-8 flex justify-center" src="{% static 'city/images/register.png' %}" alt="ثبت نام در سایت">
                    <div class="tamasha w-full border border-gray-400 my-4 rounded overflow-hidden flex">
                        <i class="fa fa-address-card phone-icon text-gray-300 p-2"></i>
                        <input type="text" name="username" class="form-control text-xs p-2 w-full h-full border-0 focus:border-0" placeholder="نام کاربری">
                    </div>
                    <div class="tamasha w-full border border-gray-400 my-4 rounded overflow-hidden flex">
                        <i class="fa fa-mobile-phone phone-icon text-gray-300 p-2"></i>
                        <input type="text" name="mobile" class="form-control text-xs p-2 w-full h-full border-0 focus:border-0" maxlength="11" placeholder="موبایل">
                    </div>

                    <div class="tamasha w-full border border-gray-400 my-4 rounded overflow-hidden flex">
                        <i class="fa fa-key phone-icon text-gray-300 p-2"></i>
                        <input type="password" name="password" class="form-control text-xs p-2 w-full h-full border-0 focus:border-0" placeholder="گذرواژه">
                    </div>
                    <div class="button-submit flex justify-end my-8">
                        <button type="submit" class="btn btn-primary w-32 h-8 rounded bg-primary text-white hover:shadow transition ease-in duration-150">ثبت نام</button>
                    </div>

                    <div class="other-link text-gray-600">
                        <a class="text-sm hover:text-gray-800 transition ease-in duration-150" href="{% url 'accounts:login' %}">
                            <i class="fa fa-user pl-2"></i>
                            ورود به سایت</a>
                        {#                <a href="#"><i class="fas fa-lock pl-2" style="font-size: 20px;"></i>رمز عبور خود را فراموش کرده ام !</a>#}
                    </div>

                </form>
            </div>
        </div>
        {% if message_in_register %}
            <div class="bg-red-300 w-96 my-8 font-vazir flex justify-center rounded p-2 mx-auto">{{ message_in_register }}</div>
        {% endif %}
    </div>
{% endblock %}