AznaCity/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('city.urls')),
    path('accounts/', include('accounts.urls')),
    # Third-Party urls
    path('ckeditor/', include('ckeditor_uploader.urls')),

]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

city/urls.py
from django.urls import path, re_path

from city import views

app_name = 'city'
urlpatterns = [
    path('', views.homepage, name='home_page'),
    # path('gardeshgari/', views.all_gardesh, name='all_gardesh'),
    # path('gardeshgari/details/<int:place_id>/', views.place_details, name='places_details'),
    re_path(r'^category/(?P<slug>[-\w]+)/$', views.category, name='unique_slug'),
    # path('main/Kaveh/<slug:slug>/', views.details, name='details'),
    re_path(r'^p/(?P<slug>[-\w]+)/$', views.place_details, name='place_details'),
    re_path(r'^p/(?P<slug>[-\w]+)/add$', views.add_sub_cat, name='add_sub_cat'),
    path('like/<int:pk_p>/<int:pk_c>/', views.like_post, name='like_post'),
    path('dislike/<int:pk_p>/<int:pk_c>/', views.dislike_post, name='dislike_post'),
]

city/forms.py
from django import forms

from city.models import Place, Soghat, SOGHAT_CATEGORY, Hotel, HOTEL_RES_CATEGORY


class AddPlaceForm(forms.ModelForm):
    class Meta:
        model = Place
        fields = ('name', 'image', 'description')

    name = forms.CharField(label='نام', max_length=50,
                           widget=forms.TextInput(
                               attrs={'class': 'rounded border border-gray-300 text-gray-800 w-full mt-4 '
                                               'mb-8 px-3 py-2 block'}))

    description = forms.CharField(label='توضیحات',
                                  widget=forms.Textarea(
                                      attrs={'class': 'rounded border border-gray-300 w-full '
                                                      'text-gray-800 mt-4 mb-8 '
                                                      'px-3 py-2 block'}))
    image = forms.CharField(label='عکس', max_length=50,
                            widget=forms.FileInput(
                                attrs={'class': 'mt-4 mb-8 block'}))


class AddSoghatForm(forms.ModelForm):
    class Meta:
        model = Soghat
        fields = ('name', 'description', 'image', 'sub_category')

    name = forms.CharField(label='نام', max_length=50,
                           widget=forms.TextInput(
                               attrs={'class': 'rounded border border-gray-300  text-gray-800 w-full mt-4 '
                                               'mb-8 px-3 py-2 block'}))

    description = forms.CharField(label='توضیحات',
                                  widget=forms.Textarea(
                                      attrs={'class': 'rounded border border-gray-300 w-full  '
                                                      'text-gray-800 mt-4 mb-8 '
                                                      'px-3 py-2 block'}))
    image = forms.CharField(label='عکس', max_length=50,
                            widget=forms.FileInput(
                                attrs={'class': 'mt-4 mb-8 block'}))

    sub_category = forms.CharField(label='دسته بندی', max_length=50,
                                   widget=forms.Select(choices=SOGHAT_CATEGORY, attrs={'class': 'rounded border '
                                                                                                'border-gray-300 mt-4 '
                                                                                                'mb-8 block '
                                                                                                ' text-gray-800'}))


class AddHotelForm(forms.ModelForm):
    class Meta:
        model = Hotel
        fields = ('name', 'image', 'sub_category', 'phone', 'address', 'description')

    name = forms.CharField(label='نام', max_length=50,
                           widget=forms.TextInput(
                               attrs={
                                   'class': 'rounded border border-gray-300 text-gray-800 w-full mt-4 '
                                            'mb-8 px-3 py-2 block'}))

    description = forms.CharField(label='توضیحات',
                                  widget=forms.Textarea(
                                      attrs={'class': 'rounded border border-gray-300 w-full  '
                                                      'text-gray-800 mt-4 mb-8 '
                                                      'px-3 py-2 block'}))
    image = forms.CharField(label='عکس', max_length=50,
                            widget=forms.FileInput(
                                attrs={'class': 'mt-4 mb-8 block'}))

    sub_category = forms.CharField(label='دسته بندی', max_length=50,
                                   widget=forms.Select(choices=HOTEL_RES_CATEGORY,
                                                       attrs={'class': 'rounded border border-gray-300 mt-4 '
                                                                       'mb-8 block  text-gray-800'}))
    address = forms.CharField(label='آدرس', max_length=50,
                              widget=forms.Textarea(
                                  attrs={'class': 'rounded border border-gray-300  text-gray-800 w-full '
                                                  'md:w-96 mt-4 mb-8 px-3 py-2 block'}))
    phone = forms.CharField(label='تلفن', max_length=50,
                            widget=forms.TextInput(
                                attrs={'class': 'rounded border border-gray-300  text-gray-800 w-full '
                                                'md:w-96 mt-4 mb-8 px-3 py-2 block'}))


class CommentForm(forms.Form):
    fields = ('fullname', 'email', 'comment')

    fullname = forms.CharField(label='نام و نام خانوادگی', required=False, max_length=50,
                               widget=forms.TextInput(
                                   attrs={'class': 'rounded border border-gray-300 text-gray-800 '
                                                   'mt-4 mb-8 px-3 py-2 text-sm w-full block'}))
    email = forms.EmailField(label='ایمیل', max_length=50, required=False,
                             widget=forms.TextInput(attrs={'class': 'rounded border border-gray-300 '
                                                                    'text-gray-800  mt-4 mb-8 px-3 py-2 '
                                                                    'text-sm w-full block'}))
    # phone = forms.CharField(label='موبایل', max_length=11, required=True,
    #                         widget=forms.TextInput(attrs={'class': 'rounded border border-gray-300 '
    #                                                                'text-gray-800  mt-4 mb-8 px-3 py-2 '
    #                                                                'text-sm w-full block'}))
    comment = forms.CharField(label='متن پیام', required=True,
                              widget=forms.Textarea(
                                  attrs={'class': 'rounded border border-gray-300 '
                                                  'text-gray-800 mt-4 mb-8 '
                                                  'px-3 py-2 w-full block'}))

# 'placeholder': 'لطفاً نام خود را وارد نمایید'
# 'placeholder': 'لطفاً ایمیل خود را وارد نمایید'
# 'placeholder': 'لطفاً شماره همراه خود را وارد نمایید'

city/views.py
from itertools import chain

from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponseRedirect
from django.urls import reverse

from .forms import AddPlaceForm, AddSoghatForm, AddHotelForm, CommentForm
from .models import City, Place, Soghat, Category, Martyrs, Hotel, Comment, IpClass

categorys = Category.objects.filter(parent=None)


def homepage(request):
    # print(categorys)
    places = Place.objects.all()
    city = City.objects.get(name='ازنا')
    gardesh = Place.objects.filter(category__slug='گردشگری', is_access=True)[:4]
    tarikhi = Place.objects.filter(category__slug='تاریخی-مذهبی', is_access=True)[:4]
    karkhane = Place.objects.filter(category__slug='کارخانجات', is_access=True)[:4]
    roosta = Place.objects.filter(category__slug='روستا', is_access=True)[:4]
    soghats = Soghat.objects.filter(is_access=True)
    martyrs = Martyrs.objects.filter(is_access=True)
    hotel_res = Hotel.objects.filter(is_access=True)
    for i in places:
        des = i.description[:50]
    context = {
        'categorys': categorys,
        'places': places,
        'city': city,
        'gardesh': gardesh,
        'tarikhi': tarikhi,
        'karkhane': karkhane,
        'roosta': roosta,
        'soghats': soghats,
        'martyrs': martyrs,
        'hotel': hotel_res,
    }
    return render(request, 'city/home_page.html', context=context)


# def all_gardesh(request):
#     all_gardeshgari = Place.objects.filter(category='T')
#     context = {
#         'all_gardeshgari': all_gardeshgari
#
#     }
#     return render(request, 'city/category.html', context=context)


def place_details(request, slug):

    list1 = [Place, Soghat, Hotel, Martyrs]
    for li in list1:
        case1 = li.objects.filter(slug=slug)
        if case1.exists():
            case = li.objects.get(slug=slug)

    ip = get_client_ip(request)
    if not IpClass.objects.filter(ip=ip).exists():
        IpClass.objects.create(ip=ip)

    case.views.add(IpClass.objects.get(ip=ip))

    context = {
        'case': case,
        'categorys': categorys,
    }

    # ******************* Start Comment *************************
    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            fullname = request.POST.get('fullname')
            email = request.POST.get('email')
            message = request.POST.get('comment')
            comment = Comment(content_object=case, fullname=fullname, email=email, comment=message)
            comment.save()
            # try:
            #     comment = comment_form.save(commit=False)
            #     comment.content_object = case
            #     comment.save()
            #     error_form = 'نظر شما با موفقیت ثبت شد.'
            # except Exception as e:
            #     error_form = str(e)
            #     print('error to save: ', str(e))
            # context['error_form'] = error_form
    else:
        comment_form = CommentForm()

    comments = Comment.objects.filter(object_id=case.id, confirm=True)
    context['comments'] = comments
    context['comment_form'] = comment_form
    # ******************* End Comment ***************************

    return render(request, 'city/places_details.html', context=context)


def category(request, slug):
    cat = Category.objects.get(slug=slug)

    place = Place.objects.filter(category__slug=slug, is_access=True)
    soghat = Soghat.objects.filter(category__slug=slug, is_access=True)
    hotel = Hotel.objects.filter(category__slug=slug, is_access=True)
    martyr = Martyrs.objects.filter(category__slug=slug, is_access=True)
    cats = list(chain(place, soghat, hotel, martyr))

    context = {
        'cat': cat,
        'cats': cats,
        'categorys': categorys,
    }

    # if cats:
    #     cat_name = cats[0].category.name
    #     cat = cats[0].category
    #     # print('cat: ', cat)
    #     context['cat_name'] = cat_name
    #     context['cat'] = cat

    return render(request, 'city/category.html', context=context)


@login_required
def add_sub_cat(request, slug):
    context = {
        'categorys': categorys,
        'slug': slug,
    }
    print('slug is: ', slug)
    if request.method == 'POST':
        if slug == 'سوغات':
            add_form = AddSoghatForm(request.POST, request.FILES)
        elif slug == 'هتل':
            add_form = AddHotelForm(request.POST, request.FILES)
        else:
            add_form = AddPlaceForm(request.POST, request.FILES)
        if add_form.is_valid():
            try:
                new = add_form.save(commit=False)
                name = request.POST.get('name')
                new.slug = "-".join(name.split())
                new.category = Category.objects.get(slug=slug)
                new.save()
                return HttpResponseRedirect(reverse('city:unique_slug', kwargs={'slug': slug}))
            except Exception as e:
                context['error_form'] = str(e)
                print('error to save: ', str(e))
        else:
            print('form oninvalid')
    else:
        if slug == 'سوغات':
            add_form = AddSoghatForm()
        # elif Q(slug == 'هتل') | Q(slug == 'رستوران'):
        elif slug == 'هتل' or slug == 'رستوران':
            add_form = AddHotelForm()
        else:
            add_form = AddPlaceForm()

    context['add_form'] = add_form

    return render(request, 'city/add_sub_cat.html', context=context)


def get_client_ip(request):
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        ip = x_forwarded_for.split(',')[0]
    else:
        ip = request.META.get('REMOTE_ADDR')
    return ip


def like_post(request, pk_p, pk_c):
    list1 = [Place, Soghat, Hotel, Martyrs]
    for li in list1:
        case1 = li.objects.filter(id=pk_p)
        if case1.exists():
            case = get_object_or_404(case1, id=pk_p)
            print('case: ', case1)

    comment = Comment.objects.get(id=request.POST.get('comment_id'))

    ip = get_client_ip(request)

    if not IpClass.objects.filter(ip=ip).exists():
        IpClass.objects.create(ip=ip)
    if comment.likes.filter(id=IpClass.objects.get(ip=ip).id).exists():
        comment.likes.remove(IpClass.objects.get(ip=ip))
    else:
        comment.likes.add(IpClass.objects.get(ip=ip))

    return HttpResponseRedirect(case.get_absolute_url())


def dislike_post(request, pk_p, pk_c):
    list1 = [Place, Soghat, Hotel, Martyrs]
    for li in list1:
        case1 = li.objects.filter(id=pk_p)
        if case1.exists():
            case = get_object_or_404(case1, id=pk_p)

    comment = Comment.objects.get(id=request.POST.get('comment_id'))

    ip = get_client_ip(request)

    if not IpClass.objects.filter(ip=ip).exists():
        IpClass.objects.create(ip=ip)
    if comment.dislikes.filter(id=IpClass.objects.get(ip=ip).id).exists():
        comment.dislikes.remove(IpClass.objects.get(ip=ip))
    else:
        comment.dislikes.add(IpClass.objects.get(ip=ip))

    return HttpResponseRedirect(case.get_absolute_url())

city/templates/city/category.html
{% extends 'city/base.html' %}
{% load static %}
{% block head %}{% endblock %}
{% block title %}{{ super }}  {{ cat }} | {% endblock %}
{% block body %}

    <main class="main-container md:max-w-screen-lg mx-auto px-2 my-8 font-vazir">
        <div class="border border-gray-200 rounded bg-white">
            {% if cat %}
                <div class="border-b-2 border-gray-300 p-6 flex items-center">
                    <h4 class="category-title text-lg">{{ cat.name }}</h4>
                </div>
                <div class="flex justify-center px-8 py-4">
                    {% if cat.image %}
                        <img class="vector-category w-2/3 md:h-144 " src="{{ cat.image.url }}" alt="{{ cat.name }}">
                    {% endif %}
                </div>

                <div class="about-category p-4">
                    <span class="text-justify leading-10">{{ cat.body|safe }}</span>
                </div>
                <div class="all-container">

                </div>
            {% else %}
                <p class="text-dark text-center bg-warning">محتوایی برای نمایش وجود ندارد ! لطفاً دسته بندی دیگری را
                    انتخاب
                    نمایید.</p>
            {% endif %}
        </div>
        <div>
            <div class="bg-white border border-gray-200 rounded p-8 grid sm:grid-cols-2 md:grid-cols-3 gap-8 my-4">
                {% for c in cats %}
                    <div class="bg-white border border-b-4 border-gray-400 rounded-lg overflow-hidden hover:shadow-lg transition ease-out duration-200">
                        <a href="{{ c.get_absolute_url }}" class="category-item-link">
                            <div class=" w-full h-40 object-cover">
                                {% if c.image %}
                                    <img class="category-item-image w-full h-full" src="{{ c.image.url }}" alt="{{ c.name }}">
                                {% endif %}
                            </div>
                            <div class="p-2">
                                <div class="md:px-2 py-2 border-b border-gray-200">
                                    <h2 class="category-item-name text-gray-700">{{ c.name }}</h2>
                                </div>
                                <div class="flex py-2">
                                    <span class="num-view ml-1 mt-1 font-vazir text-sm text-gray-400">{{ c.comments.count }}</span>
                                    <svg xmlns="http://www.w3.org/2000/svg"
                                         class="h-5 w-5 text-gray-400 ml-2"
                                         viewBox="0 0 20 20"
                                         fill="currentColor">
                                        <path d="M2 5a2 2 0 012-2h7a2 2 0 012 2v4a2 2 0 01-2 2H9l-3 3v-3H4a2 2 0 01-2-2V5z"></path>
                                        <path d="M15 7v2a4 4 0 01-4 4H9.828l-1.766 1.767c.28.149.599.233.938.233h2l3 3v-3h2a2 2 0 002-2V9a2 2 0 00-2-2h-1z"></path>
                                    </svg>
                                    <span class="num-view ml-1 mt-1 font-vazir text-sm text-gray-400">6</span>
                                    <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 text-gray-400 ml-2"
                                         fill="none" viewBox="0 0 24 24"
                                         stroke="currentColor">
                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                              d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z"></path>
                                    </svg>
                                    <span class="num-view ml-1 mt-1 font-vazir text-sm text-gray-400">{{ c.total_views }}</span>
                                    <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 text-gray-400"
                                         viewBox="0 0 20 20"
                                         fill="currentColor">
                                        <path d="M10 12a2 2 0 100-4 2 2 0 000 4z"></path>
                                        <path fill-rule="evenodd"
                                              d="M.458 10C1.732 5.943 5.522 3 10 3s8.268 2.943 9.542 7c-1.274 4.057-5.064 7-9.542 7S1.732 14.057.458 10zM14 10a4 4 0 11-8 0 4 4 0 018 0z"
                                              clip-rule="evenodd"></path>
                                    </svg>
                                </div>
                                <div class=" py-2">
                                    <span class="text-gray-600">{{ c.description|truncatewords:9|safe|escape }}</span>
                                </div>
                            </div>

                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
        <div class="border border-gray-200 rounded bg-white px-2 py-4">
            <span class="font-vazir">در این بخش شما می توانید به این دسته بندی ... خود را اضافه کنید.بعد از بررسی توسط مدیریت، ... شما در همین صفحه نمایش داده خواهد شد .</span>
            <div class="my-8">
                <a href="{% url 'city:add_sub_cat' slug=cat.slug %}" target="_blank">
                    <div class="w-24 h-24 border border-gray-400 mx-auto rounded-lg flex justify-center items-center text-gray-400 hover:text-gray-800 hover:shadow transition ease-out duration-200">
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-8 w-8" fill="none" viewBox="0 0 24 24"
                             stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                  d="M12 9v3m0 0v3m0-3h3m-3 0H9m12 0a9 9 0 11-18 0 9 9 0 0118 0z"></path>
                        </svg>

                    </div>
                </a>
                <div class="mx-auto text-center my-4">
                    <span class="text-sm">اضافه کردن</span>
                </div>
            </div>

        </div>

    </main>

    <script src="{% static 'city/js/jquery-3.5.1.min.js' %}"></script>
    <script src="{% static 'city/js/popper.min.js' %}"></script>
    <script src="{% static 'city/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'city/js/script.js' %}"></script>
{% endblock %}

city/templates/city/places_details.html
{% extends 'city/base.html' %}
{% load static %}
{% block head %}{% endblock %}
{% block title %}{{ super }} {{ case.name }} | {% endblock %}
{% block body %}
    <main class="main-container md:max-w-screen-lg mx-auto px-2 my-8 font-vazir">
        {#        <div class="container category-details-container">#}
        <div class="category-details-image-container border border-gray-200 rounded bg-white my-8">
            <div class="border-b-2 border-gray-300 p-4 md:p-6 flex items-center">
                <h1 class="category-details-name-container text-lg">
                    {% if case.category.name == 'شهدا' %}
                        <span class="text-red-600">شهید </span>{% endif %}{{ case.name }}
                </h1>
            </div>
            <div class="flex justify-center p-2 md:p-4">
                {% if case.image %}
                    <img class="category-details-image w-full md:h-144 rounded-lg" src="{{ case.image.url }}"
                         alt="{{ case.name }}">
                {% endif %}
            </div>
            <div class="px-4 py-2 md:py-4 flex items-center">
                <h1 class="category-details-name-container text-lg">
                    {% if case.category.name == 'شهدا' %}
                        <span class="text-red-600">شهید </span>{% endif %}{{ case.name }}
                </h1>
            </div>
            {% if case.category.name == 'شهدا' %}
                <div class="bg-green-200 grid md:grid-cols-3 gap-12 p-4">
                    <div class="flex flex-col gap-2">
                        <span class="font-bold text-gray-800 ml-4">نام پدر:</span>
                        <span class="text-gray-500">{% if case.father_name %}{{ case.father_name }}{% else %}
                            -{% endif %}</span>
                    </div>
                    <div class="flex flex-col gap-2">
                        <span class="font-bold text-gray-800 ml-4">تاریخ تولد:</span>
                        <span class="text-gray-500">{% if case.date_of_birth %}{{ case.date_of_birth }}{% else %}
                            -{% endif %}</span>
                    </div>
                    <div class="flex flex-col gap-2">
                        <span class="font-bold text-gray-800 ml-4">محل تولد:</span>
                        <span class="text-gray-500">{% if case.place_of_birth %}{{ case.place_of_birth }}{% else %}
                            -{% endif %}</span>
                    </div>
                    <div class="flex flex-col gap-2">
                        <span class="font-bold text-gray-800 ml-4">تاریخ شهادت:</span>
                        <span class="text-gray-500">{% if case.date_of_death %}{{ case.date_of_death }}{% else %}
                            -{% endif %}</span>
                    </div>
                    <div class="flex flex-col gap-2">
                        <span class="font-bold text-gray-800 ml-4">محل شهادت:</span>
                        <span class="text-gray-500">{% if case.place_of_death %}{{ case.place_of_death }}{% else %}
                            -{% endif %}</span>
                    </div>
                    <div class="flex flex-col gap-2">
                        <span class="font-bold text-gray-800 ml-4">عملیات:</span>
                        <span class="text-gray-500">{% if case.operation %}{{ case.operation }}{% else %}
                            -{% endif %}</span>
                    </div>
                </div>
            {% endif %}
            <div class="px-4 py-2 md:py-4">
                {% if case.biography %}
                    <p class="category-details-description-container text-justify leading-10">{{ case.biography }} </p>
                {% endif %}
                <p class="category-details-description-container text-justify leading-10">{{ case.description }}</p>
            </div>
            {% if case.will %}
                <div class="px-4 py-2 md:py-4">
                    <div class="flex items-center">
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 text-gray-500" fill="none"
                             viewBox="0 0 24 24"
                             stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                  d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z"></path>
                        </svg>
                        <h2 class="text-gray-800 my-4 mr-2 font-bold">وصیت نامه شهید {{ case.name }}</h2>
                    </div>

                    <p class="category-details-description-container text-justify leading-10">{{ case.will }} </p>
                </div>
            {% endif %}
            <div class="share-container border-t border-gray-200 p-4 flex justify-between">
                <div><span class="text-sm text-gray-600">اشتراک گذاری</span></div>
                <div class="flex gap-4">
                    <a href="" class="text-gray-600 hover:text-gray-800 transition ease-linear duration-200"><i
                            class="fa fa-telegram"></i></a>
                    <a href="" class="text-gray-600 hover:text-gray-800 transition ease-linear duration-200"><i
                            class="fa fa-twitter"></i></a>
                    <a href="" class="text-gray-600 hover:text-gray-800 transition ease-linear duration-200"><i
                            class="fa fa-facebook"></i></a>
                </div>
            </div>
        </div>
        <div class="comment-container border border-gray-200 rounded bg-white p-4">
            <div>
                <span>لطفاً نظرات خود را در مورد این مطلب به اشتراک بگذارید.نظرات شما پس از تأیید توسط مدیریت به نمایش در خواهد آمد.</span>
            </div>
            <div class="bg-gray-200 rounded-lg my-4 p-4">
                <form action="" method="post" class="grid md:grid-cols-2 gap-8">
                    {% csrf_token %}
                    {{ comment_form.as_p }}
                    <button type="submit" class="w-20 h-10 my-8 font-bold bg-yellow-400 text-gray-800 rounded">ثبت
                    </button>
                </form>
            </div>
            {% if error_form %}
                <div class="w-full rounded p-4 bg-red-300 my-8">
                    <span class="text-white font-bold text-sm">{{ error_form }}</span>
                </div>
            {% endif %}
            <div class="bg-gray-200 rounded-lg my-4 p-4">
                {% if comments %}
                    {% for c in comments %}
                        <div class="bg-white border border-gray-300 my-2 p-8 text-gray-600 font-vazir">
                            <div class="flex">
                                <span class="ml-4">{{ c.fullname }}</span>
                                <span class="comment-date">{{ c.data_add }}</span>
                            </div>
                            <div class="comment-container p-4">
                                <div class="comment py-4"><span>{{ c.comment | safe }}</span></div>
                            </div>
                            <div class="flex gap-8">
                                <form action="{% url 'city:like_post' case.id c.id %}"
                                      class="frm-like border-left-1 inline"
                                      method="post" id="frm-like-{{ c.id }}" onsubmit="submitLike({{ c.id }})">
                                    {#                                            onsubmit="submitForm({{ c.id }})"#}
                                    {% csrf_token %}
                                    <div class="value-like-dislike text-gray-400">
                                        <button type="submit" class="btn btn-sm hover:text-gray-700 transition ease-in duration-200" id="like-{{ c.id }}"
                                                name="comment_id"
                                                value="{{ c.id }}">
                                            <i class="fa fa-thumbs-up ml-2"></i>
                                        </button>
                                        <span class="total-likes font-weight-bold">{{ c.total_likes }}</span>
                                    </div>
                                </form>
                                <form action="{% url 'city:dislike_post' case.id c.id %}" class="frm-dislike inline"
                                      method="post" id="frm-dislike-{{ c.id }}"
                                      onsubmit="submitDislike({{ c.id }})">
                                    {% csrf_token %}
                                    <div class="value-like-dislike text-gray-400">
                                                <span class="font-weight-bold">{{ c.total_dislikes }}
                                                    {% if c.total_dislikes > 0 %}-{% endif %}</span>
                                        <button type="submit" class="btn btn-sm hover:text-gray-700 transition ease-in duration-200" id="dislike"
                                                name="comment_id"
                                                value="{{ c.id }}">
                                            <i class="fa fa-thumbs-down ml-2"></i>
                                        </button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    {% endfor %}
                {% else %}
                    <div class="bg-yellow-300 rounded-lg p-4 flex justify-center">
                        <span class="font-bold text-gray-700">تاکنون نظری برای این مطلب ثبت نشده است. شما اولین نفری باشید که نظر می دهد.</span>
                    </div>
                {% endif %}
            </div>
        </div>
    </main>


    <script src="{% static 'city/js/jquery-3.5.1.min.js' %}"></script>
    <script src="{% static 'city/js/popper.min.js' %}"></script>
    <script src="{% static 'city/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'city/js/script.js' %}"></script>
    <script src="{% static 'city/js/com_det.js' %}"></script>
{% endblock %}